/**
 * In a real app, this data would likely live in a database,
 * and be fetched from an API, either at runtime or at
 * compile-time.
 *
 * Keep in mind, this workshop is focused on CSS. In order
 * to make it easy to focus on the styling, we're cutting
 * some corners when it comes to our data management, and
 * our JavaScript in general. Please don't try to glean
 * any best-practices from stuff like this data file!
 */

const SHOES = [
  {
    id: 1,
    name: "NikeCourt Tech Challenge 20",
    imageSrc: "/assets/tech-challenge.jpg",
    price: 16500,
    releaseDate: Date.now() - 1000 * 60 * 60 * 1,
    numOfColors: 2,
    isNew: false,
  },
  {
    id: 2,
    name: "Nike Metcon 5 AMP",
    imageSrc: "/assets/metcon-5.jpg",
    price: 16500,
    releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 2,
    numOfColors: 1,
    isNew: false,
  },
  {
    id: 3,
    name: "Nike Phantom Vision",
    imageSrc: "/assets/phantom.jpg",
    price: 16500,
    releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 4,
    numOfColors: 4,
    isNew: true,
    discount: 5,
  },
  {
    id: 4,
    name: "Nike Air Zoom Pegasus",
    imageSrc: "/assets/pegasus.jpg",
    price: 16500,
    releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 16,
    numOfColors: 1,
    isNew: false,
  },
  {
    id: 5,
    name: "Nike Joyride Dual Run",
    imageSrc: "/assets/joyride.jpg",
    price: 17000,
    releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 40,
    numOfColors: 2,
    isNew: false,
  },
  {
    id: 6,
    name: "Nike Tiempo Legend 8",
    imageSrc: "/assets/legend-academy.jpg",
    price: 16500,
    releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 50,
    numOfColors: 8,
    isNew: true,
    discount: 7,
  },
  {
    id: 7,
    name: "Nike React Infinity Pro",
    imageSrc: "/assets/react-infinity.jpg",
    price: 16000,
    releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 75,
    numOfColors: 1,
    isNew: false,
  },
  {
    id: 8,
    name: "Nike React Phantom Run Flyknit 2",
    imageSrc: "/assets/phantom-flyknit.jpg",
    price: 18500,
    releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 100,
    numOfColors: 4,
    isNew: false,
  },
  {
    id: 9,
    name: "LeBron 17",
    imageSrc: "/assets/lebron.jpg",
    price: 26000,
    releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 120,
    numOfColors: 1,
    isNew: true,
    discount: 4,
  },
  {
    id: 10,
    name: "Air Jordan 1 Elevate Low Sneakers Women",
    imageSrc: "/assets/jordan1.webp",
    price: 24000,
    releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 120,
    numOfColors: 1,
    isNew: true,
    discount: 5,
  },
  {
    id: 10,
    name: "JORDAN STADIUM 90 - Trainers",
    imageSrc: "/assets/jordan2.webp",
    price: 27000,
    releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 120,
    numOfColors: 1,
    isNew: false,
  },
  {
    id: 11,
    name: "Nike Shoe Romaleos 4 Special Edition",
    imageSrc: "/assets/romaleos.webp",
    price: 37000,
    releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 120,
    numOfColors: 1,
    isNew: true,
    discount: 6,
  },
  {
    id: 12,
    name: "Nike air jordan luka 2",
    imageSrc: "/assets/jordan3.webp",
    price: 24000,
    releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 120,
    numOfColors: 2,
    isNew: true,
    discount: 2,
  },
  {
    id: 13,
    name: "Air Jordan 1 High OG ",
    imageSrc: "/assets/jordan4.webp",
    price: 26500,
    releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 120,
    numOfColors: 2,
    isNew: false,
  },
  {
    id: 14,
    name: "Nike Revolution 7",
    imageSrc: "/assets/revolution-7",
    price: 18500,
    releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 120,
    numOfColors: 4,
    isNew: false,
  },
];

export default SHOES;
